### ISSUE TITLE
Feature request: location tracking

### ISSUE THREAD

**Issue by Skeletorjus** [yp87/leaf2mqtt#16]
There's a fork which features a very handy location tracker (https://github.com/mitsumaui/leaf2mqtt/releases/tag/v0.5).
This would be a great addition here as well.

Thanks for your excellent work!

**Comment by yp87** [comment]
Ok I will look into it. Thank you :)

**Comment by yp87** [comment]
Hello @Skeletorjus,
I released a new version of the container with location support. Feel free to provide feedback in this issue :)

Thank you!

**Comment by Skeletorjus** [comment]
Seems to be working fine! Thanks!

**Comment by Skeletorjus** [comment]
Hi again, @yp87 

Just one further request regarding this is to send the location as json like this:
`leaf/vin/location/location: {"latitude": 00.0000000000000,"longitude": 0.000000000000}`
This makes a device_tracker available in Home Assistant simply by using
```
device_tracker:
  - platform: mqtt_json
    devices:
      Leaf: leaf/vin/location/location
```
(credit to [mitsumaui](https://github.com/mitsumaui/leaf2mqtt#home-assistant-location-integration) for this implementation)

The workaround I found is to make sensors for latitude and longitude and make an automation that sends the position to the device_tracker by way of template:
```
service: mqtt.publish
data:
  payload_template: >-
    {"latitude":{{states('sensor.leaf_location_latitude')}},"longitude":{{states('sensor.leaf_location_longitude')}}}
  topic: leaf/vin/location/location
```

Sorry if it's outside of scope.
