### ISSUE TITLE
How to start the Airco with celcius attributes.

### ISSUE THREAD

**Issue by jkulker** [yp87/leaf2mqtt#35]
Hi there,

I try this for my switch sensor but it is not working:

```
switch:
  - platform: mqtt
    name: "leaf_climate"
    state_topic: "leaf/climate/runningStatus"
    command_topic: "leaf/command/climate"
    state_on: "true"
    state_off: "false"
    payload_on: "{{'startC ' + state_attr('climate.nissan_leaf_2', 'temperature') | string() }}"
    payload_off: "stop"
    icon: mdi:hvac
```

Any ideas how to implement this correctly
