### ISSUE TITLE
binary sensor dont work

### ISSUE THREAD

**Issue by amgstone** [yp87/leaf2mqtt#53]
**Describe the bug**

**LEAF_TYPE**
The leaf type you use in your configuration

**Expected behavior**

  - name: leaf_connected
      # You can specify the vin if you prefer or if you have more than one Leaf.
    state_topic: "leaf/SJNFAAZE1U0021---/battery/connected"
    device_class: connectivity
    
  - name: leaf_charging
      # You can specify the vin if you prefer or if you have more than one Leaf.
    state_topic: "leaf/battery/charging"
    device_class: connectivity

http://joxi.ru/bmob5pqF3BLgar

http://joxi.ru/V2VvW1Nsd64Z12

**Comment by ExMacro** [comment]
This works for me so try adding the payloads into the config.

```
# Leaf2MQTT
mqtt:
  binary_sensor:
    - name: leaf_battery_charging
      # Since VIN is not specified, it will represent the state from the first vehicle in the account.
      state_topic: "leaf/battery/charging"
      payload_off: "false"
      payload_on: "true"
      device_class: battery_charging

    - name: leaf_battery_connected
      # Since VIN is not specified, it will represent the state from the first vehicle in the account.
      state_topic: "leaf/battery/connected"
      payload_off: "false"
      payload_on: "true"
      device_class: connectivity
```
